# Generated by Django 4.2.13 on 2024-05-18 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=10)),
                ('product_short_description', models.TextField(max_length=30)),
                ('product_long_description', models.TextField()),
                ('product_img', models.ImageField(upload_to='products/')),
            ],
        ),
    ]
